#commands that specify the language

language: python

python: 

- "3.6"

#command that installs dependancies

install: 
- pip install -r requirements.txt

# command to run tests

before sript:
- psql -c "CREATE DATABASE questionerdev;"-U postgres
- psql -c "CREATE USER postgres;" -U postgres
- psql -c "ALTER USER postgres WITH password 'Permafrost';"-U postgres`

branches:
  only:
    - /.*/

script : 

-  pytest

after_success:

- coveralls